name: flutter_application_1
description: "A new Flutter project."


# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # Ajusta el rango de SDK según sea necesario

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.0.12
  http: ^1.2.2 # Actualiza a una versión compatible con Flutter SDK 3.x
  flutter_unity_widget: ^4.0.0-alpha.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/ # Asegúrate de que esta carpeta exista en tu proyecto



    